version: "3.8"

services:

  limesurvey-app:
    build:
      context: ./dockerfiles/limesurvey
    volumes:
      - ./data/limesurvey/source:/var/www/html
      - ./data/limesurvey/runtime:/var/limesurvey/runtime
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
    container_name: limesurvey-app
    depends_on:
      - limesurvey-db
    environment:
      - SITE_NAME
      - ADMIN_PASSWORD
      - DB_HOST
      - PUBLIC_URL=${LETSENCRYPT_HOST}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - default

  limesurvey-redis:
    image: redis:alpine
    container_name: limesurvey-redis
    networks:
      - default
  
  limesurvey-nginx:
    image: nginx:alpine
    container_name: limesurvey-nginx
    depends_on:
      - limesurvey-app
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/limesurvey/source:/var/www/html
      - ./logs-nginx:/var/log/nginx
    networks:
      - default
      - outside

  # limesurvey-redirect:
  #   depends_on:
  #     - limesurvey-nginx
  #   build: ./dockerfiles/redirect
  #   container_name: limesurvey-redirect
  #   restart: unless-stopped
  #   environment:
  #     - VIRTUAL_HOST=${REDIRECT_ADDRESS_FROM}
  #     - HTTPS_METHOD=noredirect
  #     - LETSENCRYPT_HOST=${REDIRECT_ADDRESS_FROM}
  #     - LETSENCRYPT_EMAIL
  #     - REDIRECT=${REDIRECT_ADDRESS_TO}
  #   networks:
  #     - outside
  
  limesurvey-db:
    image: mariadb:latest
    container_name: limesurvey-db
    restart: unless-stopped
    volumes:
      - ./data/db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: ['--default-authentication-plugin=mysql_native_password','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--max_connections=301']
    networks:
      - default

networks:
  default:
    external:
      name: internal-limesurvey
  outside:
    external:
      name: services

volumes:
  lime:
